# Generated by Django 5.0 on 2024-07-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_eu',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_gl',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='news',
            name='more_info_text_ca',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Texto del botón de info'),
        ),
        migrations.AddField(
            model_name='news',
            name='more_info_text_es',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Texto del botón de info'),
        ),
        migrations.AddField(
            model_name='news',
            name='more_info_text_eu',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Texto del botón de info'),
        ),
        migrations.AddField(
            model_name='news',
            name='more_info_text_gl',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Texto del botón de info'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción corta'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción corta'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_eu',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción corta'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_gl',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción corta'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ca',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Título (máx 200 caracteres)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_es',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Título (máx 200 caracteres)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_eu',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Título (máx 200 caracteres)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_gl',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Título (máx 200 caracteres)'),
        ),
    ]
