# Generated by Django 5.0 on 2025-06-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_gl',
        ),
        migrations.RemoveField(
            model_name='news',
            name='more_info_text_ca',
        ),
        migrations.RemoveField(
            model_name='news',
            name='more_info_text_gl',
        ),
        migrations.RemoveField(
            model_name='news',
            name='short_description_ca',
        ),
        migrations.RemoveField(
            model_name='news',
            name='short_description_gl',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ca',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_gl',
        ),
    ]
