# Generated by Django 5.0 on 2024-01-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='visible',
            field=models.BooleanField(default=False, help_text='Por defecto, un nuevo mercado empieza oculto hasta que esté listo para incluir en la aplicación', verbose_name='Visible en listado público'),
        ),
    ]
