# Generated by Django 5.0 on 2024-02-14 18:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_node_additional_fields'),
        ('market', '0003_alter_account_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('logo', models.FileField(upload_to='logos_redes_sociales', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Enlace a la red social')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.socialnetwork', verbose_name='Red social')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='NodeSocialProfile',
            fields=[
                ('socialprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.socialprofile')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profiles', to='core.node', verbose_name='Mercado')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.socialprofile',),
        ),
        migrations.CreateModel(
            name='ProviderSocialProfile',
            fields=[
                ('socialprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.socialprofile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profiles', to='market.provider', verbose_name='Proveedora')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.socialprofile',),
        ),
    ]
