# Generated by Django 5.0 on 2024-02-14 18:26

from django.db import migrations


def load_social_networks(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', 'social_networks.json', app='core')


def unload_social_networks(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_socialnetwork_models'),
    ]

    operations = [
        migrations.RunPython(load_social_networks, unload_social_networks),
    ]
