# Generated by Django 5.0 on 2024-02-14 18:26
import os
from django.conf import settings
from django.db import migrations
from distutils.dir_util import copy_tree
from django.core.management import call_command


def load_social_networks(apps, schema_editor):
    copy_tree('static/imgs/logos_redes_sociales', os.path.join(settings.MEDIA_ROOT, 'logos_redes_sociales'))
    call_command('loaddata', 'social_networks.json', app='core')


def unload_social_networks(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_socialnetwork_models'),
    ]

    operations = [
        migrations.RunPython(load_social_networks, unload_social_networks),
    ]
