# Generated by Django 5.0 on 2024-02-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_load_initial_social_networks'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='takahe_server',
            field=models.URLField(blank=True, null=True, verbose_name='Servidor de Takahe'),
        ),
    ]
