# Generated by Django 5.0 on 2024-02-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_node_add_takahe_server_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='webpage_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Página web'),
        ),
    ]
