# Generated by Django 5.0 on 2024-05-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_info_page_member_card_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='has_linked_crm',
            field=models.BooleanField(default=False, verbose_name='Utiliza herramienta de gestión para las socias'),
        ),
        migrations.AddField(
            model_name='node',
            name='linked_crm_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del servidor de la Herramienta de gestión'),
        ),
    ]
