# Generated by Django 5.0 on 2024-05-22 09:17

import helpers.filesystem
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_node_has_linked_crm_node_linked_crm_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='balance_badge',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=helpers.filesystem.RandomFileName('badge/'), verbose_name='Imagen del distintivo de balance'),
        ),
    ]
