# Generated by Django 5.0 on 2024-05-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_node_balance_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='takahe_invite_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de invitación a Takahe'),
        ),
    ]
