# Generated by Django 5.0 on 2024-05-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_node_add_takahe_invite_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='Para mensajes de la herramienta', max_length=200, null=True, verbose_name='Email de administración'),
        ),
    ]
