# Generated by Django 5.0 on 2025-01-21 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_node_multilang'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizableTextContext',
            fields=[
                ('id', models.CharField(help_text='Identificador del texto', primary_key=True, serialize=False, verbose_name='Identificador')),
                ('title', models.TextField(blank=True, verbose_name='Título')),
                ('title_es', models.TextField(blank=True, null=True, verbose_name='Título')),
                ('title_ca', models.TextField(blank=True, null=True, verbose_name='Título')),
                ('title_eu', models.TextField(blank=True, null=True, verbose_name='Título')),
                ('title_gl', models.TextField(blank=True, null=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('description_ca', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('description_eu', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('description_gl', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('preview_type', models.CharField(blank=True, choices=[('email', 'Previsualizar plantilla de email'), ('form', 'Campo o explicación dentro de un formulario')], null=True, verbose_name='Previsualización')),
            ],
            options={
                'verbose_name': 'Contexto de texto personalizable',
                'verbose_name_plural': 'Contextos de texto personalizable',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomizableText',
            fields=[
                ('id', models.CharField(help_text='Identificador único del texto', primary_key=True, serialize=False, verbose_name='Identificador')),
                ('description', models.TextField(help_text='Cómo se muestra en los formularios', verbose_name='Etiqueta')),
                ('description_es', models.TextField(help_text='Cómo se muestra en los formularios', null=True, verbose_name='Etiqueta')),
                ('description_ca', models.TextField(help_text='Cómo se muestra en los formularios', null=True, verbose_name='Etiqueta')),
                ('description_eu', models.TextField(help_text='Cómo se muestra en los formularios', null=True, verbose_name='Etiqueta')),
                ('description_gl', models.TextField(help_text='Cómo se muestra en los formularios', null=True, verbose_name='Etiqueta')),
                ('help_text', models.TextField(blank=True, verbose_name='Descripción adicional')),
                ('help_text_es', models.TextField(blank=True, null=True, verbose_name='Descripción adicional')),
                ('help_text_ca', models.TextField(blank=True, null=True, verbose_name='Descripción adicional')),
                ('help_text_eu', models.TextField(blank=True, null=True, verbose_name='Descripción adicional')),
                ('help_text_gl', models.TextField(blank=True, null=True, verbose_name='Descripción adicional')),
                ('context', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customizabletextcontext', verbose_name='Contexto en el que aparece')),
            ],
            options={
                'verbose_name': 'Texto personalizable',
                'verbose_name_plural': 'Textos personalizables',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NodeCustomText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.TextField(verbose_name='Texto')),
                ('string_es', models.TextField(null=True, verbose_name='Texto')),
                ('string_ca', models.TextField(null=True, verbose_name='Texto')),
                ('string_eu', models.TextField(null=True, verbose_name='Texto')),
                ('string_gl', models.TextField(null=True, verbose_name='Texto')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_texts', to='core.node', verbose_name='Mercado')),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_values', to='core.customizabletext')),
            ],
            options={
                'verbose_name': 'Texto personalizado',
                'verbose_name_plural': 'Textos personalizados',
                'ordering': ['text_id'],
            },
        ),
    ]
