# Generated by Django 5.0 on 2025-02-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_load_customizable_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='privacy_policy_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace a la política de privacidad'),
        ),
    ]
