# Generated by Django 5.0 on 2025-06-18 08:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_node_add_privacy_policy_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizabletext',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='customizabletext',
            name='description_gl',
        ),
        migrations.RemoveField(
            model_name='customizabletext',
            name='help_text_ca',
        ),
        migrations.RemoveField(
            model_name='customizabletext',
            name='help_text_gl',
        ),
        migrations.RemoveField(
            model_name='customizabletextcontext',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='customizabletextcontext',
            name='description_gl',
        ),
        migrations.RemoveField(
            model_name='customizabletextcontext',
            name='title_ca',
        ),
        migrations.RemoveField(
            model_name='customizabletextcontext',
            name='title_gl',
        ),
        migrations.RemoveField(
            model_name='node',
            name='name_ca',
        ),
        migrations.RemoveField(
            model_name='node',
            name='name_gl',
        ),
        migrations.RemoveField(
            model_name='nodecustomtext',
            name='string_ca',
        ),
        migrations.RemoveField(
            model_name='nodecustomtext',
            name='string_gl',
        ),
        migrations.AlterField(
            model_name='node',
            name='enabled_langs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('es', 'Castellano'), ('eu', 'Euskara')], max_length=3), blank=True, default=[], size=None, verbose_name='Idiomas habilitados'),
        ),
    ]
