# Generated by Django 5.1.11 on 2025-06-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_ca_gl_langs'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='intercoop_enabled',
            field=models.BooleanField(default=False, verbose_name='Habilitar funcionalidad de intercooperación'),
        ),
    ]
