# Generated by Django 5.1.11 on 2026-08-06 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_intercoop'),
        ('market', '0017_account_remove_address_and_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Comunidad autónoma')),
                ('province', models.CharField(blank=True, max_length=250, null=True, verbose_name='Provincia')),
                ('town', models.CharField(blank=True, max_length=250, null=True, verbose_name='Municipio')),
                ('postcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código postal')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='market.account', verbose_name='Cuenta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
