# Generated by Django 5.1.11 on 2026-08-24 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_address_model'),
        ('market', '0017_account_remove_address_and_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterField(
            model_name='address',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='market.account', verbose_name='Cuenta'),
        ),
    ]
