# Generated by Django 5.1.11 on 2026-08-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_address_options_alter_address_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Provincia'),
        ),
    ]
