# Generated by Django 5.1.11 on 2026-08-26 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0013_alter_city_alternate_names_alter_city_country_and_more'),
        ('core', '0021_remove_address_province_alter_address_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.subregion', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='address',
            name='town',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities_light.city', verbose_name='Municipio'),
        ),
    ]
