yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Guía de administración de la AppMES
site_url: https://0.0.0.0/docs/admin
extra_css:
  - assets/css/extra.css

theme:
  name: material
  logo: assets/logo-mes-blanco.png
  language: es
  features:
    - navigation.instant
    - navigation.expand
    - navigation.indexes
    - toc.follow
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: orange
      toggle:
        icon: material/brightness-3
        name: Modo oscuro

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Modo claro

markdown_extensions:
  - attr_list
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.caption
  - pymdownx.blocks.tab:
      alternate_style: True
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - tags
  - i18n:
      docs_structure: folder
      languages:
        - locale: eu
          name: Euskera
          build: false
        - locale: es
          name: Castellano
          default: true
          build: true
        - locale: ca
          name: Català
          build: false
        - locale: gl
          name: Galego
          build: false

nav:
  - vista_general.md
  - acceso.md
  - perfil.md
  - idiomas.md
  - busqueda_semantica.md
  - Menú lateral:
      - menu_lateral/index.md
      - menu_lateral/personalizacion.md
      - menu_lateral/usuarias.md
      - menu_lateral/noticias.md
      - menu_lateral/categorias.md
      - menu_lateral/proveedoras.md
      - menu_lateral/consumidoras.md
      - menu_lateral/intercooperacion.md
      - menu_lateral/ofertas.md
      - menu_lateral/ventajas.md
  - Integraciones:
      - integraciones/index.md
      - integraciones/web.md
      - integraciones/api.md
      - integraciones/mapa.md
      - integraciones/herramienta_gestora.md
      - integraciones/exportar.md
      - integraciones/importar.md
  - versiones.md