# Generated by Django 5.0 on 2024-01-25 12:08

import django.core.validators
import django.db.models.deletion
import helpers.filesystem
import imagekit.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('cif', models.CharField(max_length=30, verbose_name='NIF/CIF/Pasaporte')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('member_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de socia')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='Municipio')),
                ('profile_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=helpers.filesystem.RandomFileName('profiles/'), verbose_name='Imagen de perfil')),
                ('last_updated', models.DateTimeField(blank=True, null=True, verbose_name='Última actualización')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.node')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gestionado por')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color de etiqueta (código hexadecimal)')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.node')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.account')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Descripción corta')),
                ('not_listed', models.BooleanField(default=False, verbose_name='Oculta en listado público')),
                ('latitude', models.FloatField(default=0, verbose_name='Latitud')),
                ('longitude', models.FloatField(default=0, verbose_name='Longitud')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono')),
                ('num_workers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de trabajadores')),
                ('legal_form', models.TextField(blank=True, null=True, verbose_name='Formulario legal')),
                ('balance_detail', models.CharField(blank=True, max_length=250, null=True, verbose_name='Informe balance')),
                ('facebook_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Página de Facebook')),
                ('webpage_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Página web')),
                ('twitter_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil de X')),
                ('telegram_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Canal de Telegram')),
                ('instagram_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil de Instagram')),
                ('fediverse_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil en Fediverso')),
                ('categories', models.ManyToManyField(blank=True, to='market.category', verbose_name='Categorías')),
                ('gallery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gallery')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'ordering': ['name'],
            },
            bases=('market.account',),
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.account')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Apellidos')),
                ('is_intercoop', models.BooleanField(default=False, verbose_name='Es socia de intercooperación')),
                ('favorites', models.ManyToManyField(blank=True, to='market.provider', verbose_name='Favoritos')),
            ],
            options={
                'verbose_name': 'Consumidora',
                'verbose_name_plural': 'Consumidoras',
            },
            bases=('market.account',),
        ),
    ]
