# Generated by Django 5.0 on 2024-01-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['name'], 'verbose_name': 'Proveedora', 'verbose_name_plural': 'Proveedoras'},
        ),
    ]
