# Generated by Django 5.0 on 2024-01-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='market.provider', verbose_name='Favoritos'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='is_intercoop',
            field=models.BooleanField(default=False, verbose_name='Es socia de intercooperación'),
        ),
    ]
