# Generated by Django 5.0 on 2024-02-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_account_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='fediverse_link',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='twitter_link',
        ),
    ]
