# Generated by Django 5.0 on 2024-04-11 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_provider_remove_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='registration_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Fecha de alta'),
        ),
    ]
