# Generated by Django 5.0 on 2024-05-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_default_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono'),
        ),
    ]
