# Generated by Django 5.0 on 2025-02-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_provider_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='services_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Productos y servicios'),
        ),
        migrations.AddField(
            model_name='provider',
            name='services_es',
            field=models.TextField(blank=True, null=True, verbose_name='Productos y servicios'),
        ),
        migrations.AddField(
            model_name='provider',
            name='services_eu',
            field=models.TextField(blank=True, null=True, verbose_name='Productos y servicios'),
        ),
        migrations.AddField(
            model_name='provider',
            name='services_gl',
            field=models.TextField(blank=True, null=True, verbose_name='Productos y servicios'),
        ),
    ]
