# Generated by Django 5.0 on 2025-02-19 21:32

import helpers.filesystem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_add_services_field_to_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='idcard_file',
            field=models.FileField(blank=True, null=True, upload_to=helpers.filesystem.RandomFileName('dnis/'), verbose_name='Documento identificativo (DNI/NIE/Pasaporte...)'),
        ),
    ]
