# Generated by Django 5.0 on 2025-02-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_consumer_idcard_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='newsletter_check',
            field=models.BooleanField(default=False, help_text='Aceptas recibir el boletín informativo cono noticias y ventajas/ofertas para socias en formato electrónico', verbose_name='Boletín de difusión'),
        ),
    ]
