# Generated by Django 5.0 on 2025-02-25 13:21

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_consumer_newsletter_check'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='provider',
            name='embedding_description',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True, verbose_name='Descripción y productos vectorizados'),
        ),
    ]
