# Generated by Django 5.0 on 2025-06-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_pgvector_extension_and_add_provider_embedding_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_gl',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ca',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_gl',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='description_ca',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='description_gl',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='legal_form_ca',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='legal_form_gl',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='name_ca',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='name_gl',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='services_ca',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='services_gl',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='short_description_ca',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='short_description_gl',
        ),
    ]
