# Generated by Django 5.1.11 on 2025-06-18 13:59

import django.db.models.deletion
import helpers.filesystem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_intercoop'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='idcard_file2',
            field=models.FileField(blank=True, help_text='En caso de que hayas subido una foto con únicamente la parte delantera de tu documento, puedes subir aquí la trasera', null=True, upload_to=helpers.filesystem.RandomFileName('dnis/'), verbose_name='Documento identificativo (reverso)'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='intercoop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.intercoop', verbose_name='Intercooperación'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='intercoop_external_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Identificador de socia externa'),
        ),
    ]
