# Generated by Django 5.1.11 on 2025-11-10 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_consumer_intercoop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='num_workers',
        ),
        migrations.AlterField(
            model_name='consumer',
            name='intercoop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.intercoop', verbose_name='Intercooperación'),
        ),
        migrations.AlterField(
            model_name='intercoop',
            name='external_id_label',
            field=models.CharField(blank=True, help_text='Por ejemplo, "Número de socia"', max_length=200, null=True, verbose_name='Etiqueta del identificador en el formulario'),
        ),
        migrations.AlterField(
            model_name='intercoop',
            name='external_id_label_es',
            field=models.CharField(blank=True, help_text='Por ejemplo, "Número de socia"', max_length=200, null=True, verbose_name='Etiqueta del identificador en el formulario'),
        ),
        migrations.AlterField(
            model_name='intercoop',
            name='external_id_label_eu',
            field=models.CharField(blank=True, help_text='Por ejemplo, "Número de socia"', max_length=200, null=True, verbose_name='Etiqueta del identificador en el formulario'),
        ),
    ]
