# Generated by Django 5.1.11 on 2025-11-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_provider_balance_detail_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='num_workers',
        ),
    ]
