# Generated by Django 5.1.11 on 2026-08-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_remove_provider_num_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='contact_address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección de contacto'),
        ),
    ]
