# Generated by Django 5.1.11 on 2026-08-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_remove_provider_num_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='city',
        ),
    ]
