# Generated by Django 5.0 on 2024-07-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_set_offer_date_to_current_date_as_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_eu',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description_gl',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='offer',
            name='title_ca',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Título de la oferta'),
        ),
        migrations.AddField(
            model_name='offer',
            name='title_es',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Título de la oferta'),
        ),
        migrations.AddField(
            model_name='offer',
            name='title_eu',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Título de la oferta'),
        ),
        migrations.AddField(
            model_name='offer',
            name='title_gl',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Título de la oferta'),
        ),
    ]
