# Generated by Django 5.0 on 2024-02-20 10:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_api_token_proxy'),
        ('market', '0003_alter_account_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegisteredUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email preregistro enviado')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.account', verbose_name='Cuenta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preregister', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prerregistro',
                'verbose_name_plural': 'Prerregistros',
                'ordering': ['user'],
            },
        ),
    ]
