# Generated by Django 5.0 on 2024-07-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='benefit_for_entities_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Ventajas para entidades'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='benefit_for_entities_es',
            field=models.TextField(blank=True, null=True, verbose_name='Ventajas para entidades'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='benefit_for_entities_eu',
            field=models.TextField(blank=True, null=True, verbose_name='Ventajas para entidades'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='benefit_for_entities_gl',
            field=models.TextField(blank=True, null=True, verbose_name='Ventajas para entidades'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='benefit_for_members_ca',
            field=models.TextField(blank=True, null=True, verbose_name='Ventajas para socias'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='benefit_for_members_es',
            field=models.TextField(blank=True, null=True, verbose_name='Ventajas para socias'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='benefit_for_members_eu',
            field=models.TextField(blank=True, null=True, verbose_name='Ventajas para socias'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='benefit_for_members_gl',
            field=models.TextField(blank=True, null=True, verbose_name='Ventajas para socias'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='discount_link_text_ca',
            field=models.CharField(blank=True, default='Solicitar descuento', max_length=100, null=True, verbose_name='Texto del botón del link de descuento'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='discount_link_text_es',
            field=models.CharField(blank=True, default='Solicitar descuento', max_length=100, null=True, verbose_name='Texto del botón del link de descuento'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='discount_link_text_eu',
            field=models.CharField(blank=True, default='Solicitar descuento', max_length=100, null=True, verbose_name='Texto del botón del link de descuento'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='discount_link_text_gl',
            field=models.CharField(blank=True, default='Solicitar descuento', max_length=100, null=True, verbose_name='Texto del botón del link de descuento'),
        ),
    ]
