name: Publish docs
on:
  push:
    branches:
      - main

jobs:
  publish_admin_docs:
    name: Deploy admin docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-static-i18n[material]
          pip install mkdocs-awesome-pages-plugin

      - name: Build MkDocs
        run: |
          cd documentation/admin
          mkdocs build
          zip -r admin_docs.zip site

      - name: Create artifcat
        uses: actions/upload-artifact@v4
        with:
          name: admin_docs
          path: documentation/admin/admin_docs.zip

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "documentation/admin/site"
          target: "${{ secrets.PROJECT_PATH }}"

  publish_user_docs:
    name: Deploy user docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-static-i18n[material]
          pip install mkdocs-awesome-pages-plugin

      - name: Build MkDocs
        run: |
          cd documentation/user
          mkdocs build
          zip -r user_docs.zip site

      - name: Create artifcat
        uses: actions/upload-artifact@v4
        with:
          name: user_docs
          path: documentation/user/user_docs.zip

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "documentation/user/site"
          target: "${{ secrets.PROJECT_PATH }}"
